version: "3"

services:
  oidc-agent:
    image: opensciencegrid/oidc-agent:3.6-release-20230802-1615
    platform: linux/amd64

  base:
    build:
      context: ../.
      target: development
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    depends_on:
      - db
    volumes:
      - ..:/workspace:cached
    # Infinite loop to keep container live doing nothing
    command: bash -c "while true; do sleep 1; done"
