trusted_idps:
  - issuer: https://idp.test.com/
    group_claim: groups
    user_groups:
      - name: test1
        slas:
          - doc_uuid: edfda059a23c439f8ffc06edd484e1a0
            start_date: 2023-09-10
            end_date: 2024-09-25
          - doc_uuid: c2bb880f0aa443a49abcbbbe2e96b48b
            start_date: 2023-10-11
            end_date: 2023-10-25

openstack:
  - name: test-provider1
    status: active
    is_public: false
    support_emails:
      - admin@test.it
    image_tags: [test-tag1]
    network_tags: [test-tag2]
    block_storage_vol_types:
      gold: test-type1
      silver: test-type2
    regions:
      - name: test-region1
        location:
          site: test-site1
          country: Italy
      - name: test-region2
        location:
          site: test-site2
          country: Italy
    auth_url: https://keystone.test.it/
    identity_providers:
      - endpoint: https://idp.test.com/
        name: my-test-idp
        protocol: openid
    projects:
      - id: 12bb88070aa443a494bcbbbe2e96b48b
        sla: c2bb880f0aa443a49abcbbbe2e96b48b
        per_region_props:
          - region_name: test-region1
            default_public_net: test-public-net1
            default_private_net: test-private-net1
            private_net_proxy:
              ip: 10.21.1.1
              user: test-user1
            per_user_limits:
              compute:
                cores: 2
                ram: 2
              block_storage:
                gigabytes: 2
          - region_name: test-region2
            default_public_net: test-public-net2
            default_private_net: test-private-net2
            private_net_proxy:
              ip: 10.24.1.2
              user: test-user2
            per_user_limits:
              compute:
                cores: 3
                ram: 2
              block_storage:
                gigabytes: 10
                per_volume_gigabytes: 2
                volumes: 5
